# Generated by Django 4.1.5 on 2023-01-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonAPI",
            "0003_remove_orderitem_price_remove_orderitem_unit_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="LittleLemonAPI.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("menuitem", "order")},
        ),
    ]
